CREATE OR REPLACE PACKAGE epf_purge AUTHID DEFINER AS
-- ============================================================================
-- EPF Data Purge - Purge engine
-- ============================================================================
-- Purges the registry tables of the modules selected by a run, driven only by
-- the registry (EPF_TABLE, EPF_LINK) and the live foreign keys.
--
-- Eligibility
--   Root       date_column < cutoff date of the run.
--   Dependent  match_column in the keys of an eligible source row (per link;
--              several links are combined). A link whose source column is not
--              the source key column is a reverse link: the source row points
--              at the dependent row. A dependent row still pointed at by a
--              retained source row is kept (held row).
--   Held root  when a row that is kept (outside the eligible set, or in a
--              table outside the registry) references, through an enabled
--              FK, a row of an eligible root's tree, that root and its whole
--              tree are left for a later run. Repeated until no reference
--              remains. Applies to deleting modules.
--
-- Key snapshot (EPF_WORK_KEY, a global temporary table private to the
-- purging session: no redo; its undo goes to the temporary tablespace)
--   Root keys are taken once, then the keys of every link source below the
--   root are derived with the root they belong to. Roots are numbered into
--   batches in key order; roots whose trees reference each other through an
--   FK share a batch. A batch holds at most batch_size roots and about the
--   run's batch_rows rows (setting batch_rows_max): the rows of a root are
--   its keys in each table with keys times the rows of the tree per key of
--   that table (optimizer statistics); a tree without link sources with keys
--   below its root counts the same rows for every root. A root whose tree
--   alone passes the limit is a batch of its own. A root without key column
--   (and without dependents) is snapshot by ROWID in physical order and its
--   rows are re-checked against the cutoff when processed.
--
-- Actions per module
--   DELETE  modes FULL and LOGS, and the LOGS module in mode CLOB_N_LOGS.
--   CLEAR   modes CLOB and CLOB_N_LOGS (other modules): LOB columns of
--           eligible rows (tables with lob_clear = Y) are set to an empty
--           LOB where their length is above zero. lob_throttle_ms is waited
--           after every batch.
--   Each batch is one transaction: tables in ascending delete_order (leaves
--   first, root last). A failing batch is rolled back and stops its module;
--   the other modules continue. A stop request is honoured between batches.
--
-- Supporting indexes
--   Missing indexes are created for the duration of a module:
--   EPF_TMP_<run>_<n>, owned by the tool schema in its default tablespace,
--   recorded in EPF_TEMP_INDEX and dropped when the module ends.
--     link  a link column (and the source column of a reverse link), read
--           once per batch: on tables of at least temp_index_min_mb
--     fk    in a deleting module, the columns of every enabled FK into its
--           tables: Oracle looks up child rows for every deleted parent row
--           and scans the child table when these columns are not indexed,
--           so they are indexed whatever the table size. A child table
--           outside the registry cannot be indexed and is reported.
--   Indexes left by an interrupted run are dropped at the start of the next
--   purge.
--
-- Counts (EPF_TABLE_STAT, phases BEFORE and AFTER)
--   total, eligible, retained (total - eligible), non-empty LOB values
--   (CLEAR), processed (AFTER), held, orphans, action; the redo and undo of
--   the purge's statements on the table (AFTER) and the redo per row
--   estimated from optimizer statistics (BEFORE, deleting). Orphans per link
--   (EPF_LINK_STAT): rows on the pointing side whose value is not found on
--   the pointed side; a link protected by an enabled, validated FK is not
--   scanned. Space inside segments is captured with epf_space (BASELINE, and
--   POST_PURGE unless dry run).
--
-- Compaction (with_compact = Y, purge-only runs, step COMPACT)
--   Registry tables of deleting modules whose table segment has at least
--   compact_min_free_pct free after the purge are shrunk (row movement
--   enabled and restored, SHRINK SPACE COMPACT, SHRINK SPACE CASCADE or the
--   table alone when the cascade is refused), largest free space first;
--   space is captured again (POST_COMPACT).
--
-- Events: PURGE_SCOPE, TABLE_SKIPPED, ROOT_MISSING, TEMP_INDEX_LEFTOVER,
--   KEYS_SNAPSHOT, ROOTS_HELD, ROOTS_GROUPED, TABLE_ELIGIBLE, TEMP_INDEX_CREATED,
--   TEMP_INDEX_FAILED, TEMP_INDEX_DROPPED, TEMP_INDEX_KEPT, FK_UNINDEXED,
--   BATCH_PROGRESS, BATCH_FAILED,
--   STOP_HONORED, TREE_REDO, TREE_UNDO, TABLE_RESULT, LINK_ORPHANS, COMPACTED,
--   COMPACT_SKIPPED, COMPACT_FAILED, ROW_MOVEMENT_KEPT, MODULE_END, STEP_FAILED,
--   IDX_MISSING, IDX_SUMMARY, ROOTS_ELIGIBLE, REDO_LOGS, REDO_ESTIMATE,
--   REDO_SUMMARY, UNDO, UNDO_ESTIMATE, UNDO_TUNING, REQUIREMENTS, FORECAST,
--   ROOTS_RECOUNTED, REQUIREMENTS_NOT_MET, CHOICES, PURGE_END.
--
-- Requirements (preflight step REQUIREMENTS; EPF_REQUIREMENT, EPF_REQ_OPTION)
--   Six conditions for a purge to run to its end, each with the ways to meet
--   it and which of them meets it now:
--     ARCHIVE      archived logs fit the archive destination (ARCHIVELOG):
--                  redo estimate + archive_margin_pct against the free space
--                  of the recovery area or ASM disk group; a directory cannot
--                  be measured from the database
--     UNDO         the undo tablespace holds 4 batches and the undo kept for
--                  undo_retention, or undo tuning limits it
--     TEMP         TEMP holds the work keys
--     INDEX_SPACE  the tool's tablespace holds the temporary indexes
--     REDO_LOGS    one batch fits an online log (otherwise only slower)
--     BACKUP       an RMAN database backup newer than backup_max_age_h, or
--                  the run's backup_choice (CONFIRMED, NONE)
--   ARCHIVE, UNDO, TEMP and BACKUP are blocking. The operator can confirm
--   ARCHIVE, UNDO and TEMP as handled (EPF_RUN.confirmed_reqs), for example
--   an archive directory whose free space the database cannot read. A purge
--   that deletes does not start while a blocking requirement of its
--   preflight is not met (REQUIREMENTS_NOT_MET, status FAILED). Root counts
--   are kept per month (EPF_ROOT_MONTH: the largest purge that fits the
--   archive space) and for 1.5, 2 and 3 times the retention
--   (EPF_RETENTION_OPTION). A purge's preflight reuses the root counts of
--   the preflight run whose choices it follows (same cutoff, mode and depth,
--   within preflight_valid_h, no purge since) instead of counting again.
--   The operator's choices (batch size, undo tuning, redo log sizing,
--   backup, confirmations) are kept with the run; recheck evaluates the
--   requirements again with them. Redo log sizing planned counts as 1 GB
--   online logs.
--
-- Forecast (EPF_FORECAST, per module)
--   The preflight forecasts roots, batches, redo, undo (estimates per root,
--   EPF_TREE_EST) and the deleting time of the rows the roots carry (rows
--   per root). A dry run ends with step FORECAST: exact rows and roots after
--   holding back, its batches, the space freed inside the segments (used
--   space x eligible share), and redo and undo per row: the rows counted in
--   each table times the redo and undo per row measured for the table by the
--   latest purge that processed enough of its rows, else measured for its
--   tree, else the estimate per row from optimizer statistics (roots of
--   different ages carry very different numbers of rows, so a cost per root
--   does not carry over). Deleting time: the rows of each tree at the rows
--   per second measured for the tree by its latest purge, else by the latest
--   purge on the database, else the setting delete_rows_s plus a fixed time
--   per batch. The report of a purge compares its result with the latest
--   forecast.
--
-- Redo
--   The redo written by each root tree is measured (V$MYSTAT) and recorded
--   as TREE_REDO (rows = roots processed, bytes = redo, elapsed seconds),
--   and by the statements on each table (EPF_TABLE_STAT). Preflight compares
--   the redo of a batch with the online redo logs and recommends a batch
--   size; it uses the latest measurement of each tree, or an estimate from
--   optimizer statistics when the tree has not been purged yet.
--
-- Undo
--   Undo is measured the same way (TREE_UNDO, with the elapsed time, so the
--   undo rate is known). Preflight (step UNDO) reports the undo tablespace,
--   the undo of a batch and, from the measured rate, how much undo
--   undo_retention keeps during the purge. Undo tuning (epf_tuning, SYS)
--   lowers undo_retention and caps undo growth for the purge; a run reports
--   at its start and end whether it is active.
--
-- Error codes
--   ORA-20130  run is not a purge / preflight run, or session not bound to it
--   ORA-20131  held roots did not converge
-- ============================================================================

    -- Read-only checks for run p_run_id (action PURGE or PREFLIGHT) in the
    -- session bound to it: registry validation (step REGISTRY), supporting
    -- indexes (SUPPORTING_INDEXES), eligible roots (ELIGIBLE_ROOTS), online
    -- redo logs with the recommended batch size (REDO_LOGS), undo (UNDO),
    -- the requirements (REQUIREMENTS) and the forecast (FORECAST) of the
    -- modules in scope. p_reuse_run: a PREFLIGHT run whose root counts are
    -- reused when still valid. Writes only the tool's own tables.
    PROCEDURE preflight(p_run_id IN NUMBER, p_errors OUT PLS_INTEGER, p_warnings OUT PLS_INTEGER,
                        p_reuse_run IN NUMBER DEFAULT NULL);

    -- After the operator's choices are saved with run p_run_id
    -- (epf_control.set_choices), checks the redo logs, undo and requirements
    -- again and redoes the forecast, from the root counts its preflight kept
    -- (step CHOICES, event CHOICES; no table is scanned). In the session
    -- bound to the run.
    PROCEDURE recheck(p_run_id IN NUMBER, p_warnings OUT PLS_INTEGER);

    -- Runs the purge phase of run p_run_id (action PURGE) in the session bound
    -- to it (epf_control.attach / enter). p_status returns SUCCESS, WARNING,
    -- FAILED or STOPPED. A dry run stops after the counts and its forecast.
    PROCEDURE run(p_run_id IN NUMBER, p_status OUT VARCHAR2);

    -- Free space for archived logs: the smallest free space of the valid
    -- local archive destinations (recovery area: limit - used + reclaimable;
    -- ASM disk group: free). NULL when a destination cannot be measured from
    -- the database (a directory); p_where describes every destination. Also
    -- used by the reclaim's requirement ARCHIVE.
    PROCEDURE archive_room(p_room OUT NUMBER, p_where OUT VARCHAR2);

END epf_purge;
/
